# Template

Start with one paragraph overview.

A script with all the R code in the chapter can be downloaded
[here](./Rcode/template.R). The Rmd for this chapter can be downloaded
[here](./Rmds/template.Rmd).

### Data and packages

All the data used in the chapter are in the **MARSS** package. Install
the package, if needed, and load to run the code in the chapter.

    library(MARSS)

## Introduction

Introdution. Here’s how to do an equation with numbering.

## New section

New section. Example of an equation with matrix.

and the process model would look like

The observation errors would be

And the process errors would be

## Section 3

Another section.

## Discussion

For your homework this week, we will continue to investigate common
trends in the Lake Washington plankton data.

1.  Fit other DFA models to the phytoplankton data with varying numbers
    of trends from 1-4 (we fit a 3-trend model above). Do not include
    any covariates in these models. Using `R="diagonal and unequal"` for
    the observation errors, which of the DFA models has the most support
    from the data?

    Plot the model states and loadings as in Section
    @ref(sec-dfa-estimated-states). Describe the general patterns in the
    states and the ways the different taxa load onto those trends.

    Also plot the the model fits as in Section @ref(sec-dfa-plot-data).
    Do they reasonable? Are there any particular problems or outliers?

2.  How does the best model from Question 1 compare to a DFA model with
    the same number of trends, but with `R="unconstrained"`?

    Plot the model states and loadings as in Section
    @ref(sec-dfa-estimated-states). Describe the general patterns in the
    states and the ways the different taxa load onto those trends.

    Also plot the the model fits as in Section @ref(sec-dfa-plot-data).
    Do they reasonable? Are there any particular problems or outliers?

3.  Fit a DFA model that includes temperature as a covariate and 3
    trends (as in Section @ref(sec-dfa-lakeWA)), but
    with`R="unconstrained"`? How does this model compare to the model
    with `R="diagonal and unequal"`? How does it compare to the model in
    Question 2?

    Plot the model states and loadings as in Section
    @ref(sec-dfa-estimated-states). Describe the general patterns in the
    states and the ways the different taxa load onto those trends.

    Also plot the the model fits as in Section @ref(sec-dfa-plot-data).
    Do they reasonable? Are there any particular problems or outliers?
